import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a2837",
        "secondary": "#a0cafc",
        "surface-container-lowest": "#0e0d1a",
        "on-tertiary": "#322f34",
        "primary": "#a5e7ff",
        "surface-tint": "#47d6ff",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "tertiary-container": "#c5bfc5",
        "on-surface-variant": "#bbc9cf",
        "inverse-on-surface": "#302f3e",
        "on-secondary-container": "#92bced",
        "on-secondary-fixed": "#001d36",
        "on-error": "#690005",
        "surface-variant": "#353343",
        "primary-fixed-dim": "#47d6ff",
        "tertiary-fixed": "#e7e0e6",
        "surface": "#131220",
        "on-tertiary-fixed": "#1d1b1f",
        "on-primary": "#003543",
        "on-primary-fixed-variant": "#004e60",
        "error": "#ffb4ab",
        "on-primary-container": "#00566a",
        "on-primary-fixed": "#001f28",
        "primary-container": "#00d2ff",
        "surface-dim": "#131220",
        "tertiary": "#e1dbe1",
        "surface-bright": "#393747",
        "secondary-fixed": "#d1e4ff",
        "on-tertiary-fixed-variant": "#49454a",
        "outline-variant": "#3c494e",
        "outline": "#859399",
        "on-secondary-fixed-variant": "#1a4974",
        "secondary-container": "#1d4b77",
        "background": "#11101E",
        "surface-container-highest": "#353343",
        "inverse-primary": "#00677f",
        "on-surface": "#e4e0f5",
        "surface-container-low": "#1b1a28",
        "secondary-fixed-dim": "#a0cafc",
        "on-background": "#e4e0f5",
        "on-secondary": "#003258",
        "inverse-surface": "#e4e0f5",
        "on-tertiary-container": "#514d52",
        "surface-container": "#1f1e2d",
        "primary-fixed": "#b6ebff",
        "tertiary-fixed-dim": "#cbc5ca"
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)"],
        body: ["var(--font-manrope)"],
        label: ["var(--font-inter)"],
      },
    },
  },
  plugins: [],
};
export default config;
